### ISSUE TITLE
Something fishy about IplClipLineToImage

### ISSUE THREAD

**Issue by bnascimento** [Krigu/Gaze#1]
bool IplClipLineToImage( IplImage\* img, double& x0, double& y0, double& x1, double& y1 )
{
    int outCode0,outCode1;
    double m = 0.0;
    if( x0 != x1 )
        m = (double)(y1 - y0)/ (double)(x1 - x0);
    int x = 0;
    int y = 0;

```
while( true )
```

... sometimes never leaves this while.....

**Comment by flurischt** [comment]
@bnascimento this never happened with our use cases. do you have some example code or an image with which the problem is reproducible?
